// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-lfkXf6TSgACM66fXTGfk1l3RkkLypqg',
    appId: '1:368136691749:web:423c0f56d1d0204b22dfcc',
    messagingSenderId: '368136691749',
    projectId: 'criptomoedas-d3ce2',
    authDomain: 'criptomoedas-d3ce2.firebaseapp.com',
    storageBucket: 'criptomoedas-d3ce2.appspot.com',
    measurementId: 'G-91X1611MFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzMDRMf-ShsjtjO-NSfh9_qn8-AQUOV18',
    appId: '1:368136691749:android:38ef085cb36a747622dfcc',
    messagingSenderId: '368136691749',
    projectId: 'criptomoedas-d3ce2',
    storageBucket: 'criptomoedas-d3ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfRV4iLwWD9GwYyefFkUkOgExrbSU9Vk',
    appId: '1:368136691749:ios:b1ad9d5ca768b2d022dfcc',
    messagingSenderId: '368136691749',
    projectId: 'criptomoedas-d3ce2',
    storageBucket: 'criptomoedas-d3ce2.appspot.com',
    iosClientId: '368136691749-g3clqc44slqkaj8ho567s4vj0nvj98br.apps.googleusercontent.com',
    iosBundleId: 'com.example.cripto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSfRV4iLwWD9GwYyefFkUkOgExrbSU9Vk',
    appId: '1:368136691749:ios:b1ad9d5ca768b2d022dfcc',
    messagingSenderId: '368136691749',
    projectId: 'criptomoedas-d3ce2',
    storageBucket: 'criptomoedas-d3ce2.appspot.com',
    iosClientId: '368136691749-g3clqc44slqkaj8ho567s4vj0nvj98br.apps.googleusercontent.com',
    iosBundleId: 'com.example.cripto',
  );
}
